### ISSUE TITLE
Sponsors Section

### ISSUE THREAD

**Issue by sunyu912** [gamegala/gamegala.github.io#11]
Let's use the same text

SPONSORES
Welcome to the dedicated to building remarkable Sponsors!

And also the same background image.

**Comment by cassilam** [comment]
added sub heading and background img

**Comment by sunyu912** [comment]
Let's also add this one. If the ratio does not fit well, we can put it in a white background image with the right ratio dimension, and then scale it.

http://www.churchsake.com/

**Comment by cassilam** [comment]
Added ChurchSake to sponsors list
