### ISSUE TITLE
Replace the new logo

### ISSUE THREAD

**Issue by sunyu912** [gamegala/gamegala.github.io#21]
Hi Cassi, please take a look which one looks better:

![galastackedv1](https://user-images.githubusercontent.com/1639351/48461862-aab08b80-e78a-11e8-9138-76da4556b4cf.png)

![galahorizontalv1](https://user-images.githubusercontent.com/1639351/48461864-ae441280-e78a-11e8-98ea-5a995fc1fe3f.png)

**Comment by cassilam** [comment]
I think the second one looks better. I'll update the logo

**Comment by cassilam** [comment]
Is it possible to change the E in the circle to a G?

**Comment by sunyu912** [comment]
That would probably be difficult. I think we can just use this one for now.

Yu

**Comment by cassilam** [comment]
Replaced the logo
