### ISSUE TITLE
Change "8" in 2018 from White to a different color

### ISSUE THREAD

**Issue by sunyu912** [gamegala/gamegala.github.io#24]
<img width="770" alt="screen shot 2018-11-14 at 4 41 59 pm" src="https://user-images.githubusercontent.com/1639351/48522123-47773580-e82c-11e8-9927-336391d8ff41.png">

Maybe this color:

<img width="111" alt="screen shot 2018-11-14 at 4 42 57 pm" src="https://user-images.githubusercontent.com/1639351/48522154-607fe680-e82c-11e8-9250-72fdd59032c6.png">

**Comment by cassilam** [comment]
Changed it to iris blue
