### ISSUE TITLE
Add Sponsor

### ISSUE THREAD

**Issue by sunyu912** [gamegala/gamegala.github.io#25]
Probably not the whole - maybe only the left hand side.

https://lh3.googleusercontent.com/CLYckDoeRf93ps92NCIcmi7wxmn5geNIZG1uTDof_CN6AozQhSnm8hQOz1lzkBlP6B0qRVj5O0Kh81REs27VGhZ1O0_loy2bwrqGeEyVf2t5itgVVuaqBte1DcR0DEyidIbLJnTU

**Comment by cassilam** [comment]
Added Computer Science Society to sponsors
