### ISSUE TITLE
Add Sponsor

### ISSUE THREAD

**Issue by sunyu912** [gamegala/gamegala.github.io#26]
https://mail.google.com/mail/u/0?ui=2&ik=631830a7b5&attid=0.1&permmsgid=msg-f:1617510072072146385&th=16728cd7327a0dd1&view=fimg&sz=s0-l75-ft&attbid=ANGjdJ8S7wfH58bfSI8m6IcRzT0s4Gx3AAQUbjSfOyMZLUyGKBUS718jm16bHGH8MjM-2hMtyyEviUOXl2BRNDe4beizzkBO-At9_3mxogc__-8EET0uNfPXzAhZGSs&disp=emb

**Comment by cassilam** [comment]
Received a 410 error when trying to open the link

**Comment by cassilam** [comment]
Added Kronosaur Productions to sponsors list
