### ISSUE TITLE
Text Change

### ISSUE THREAD

**Issue by sunyu912** [gamegala/gamegala.github.io#7]
Data/Time: December 16th, 9:00 AM - 3:30 PM
Location: California Science Center
Address: 700 Exposition Park Dr, Los Angeles, CA 90037
Parking: (CASH ONLY)
Parking for cars is $12 until 5:00 p.m. and $15 after 5:00 p.m.
Parking for Charter buses and oversize vehicles is $30.
Click Here For Driving Instructions
=>
Data/Time: December 16th, 9:00 AM - 3:00 PM
Location: Muses Room @ California Science Center
Address: 700 Exposition Park Dr, Los Angeles, CA 90037
Parking: (CASH ONLY)
Parking for cars is $12 until 5:00 p.m. and $15 after 5:00 p.m.
Parking for Charter buses and oversize vehicles is $30.
Click Here For Driving Instructions

**Comment by cassilam** [comment]
updated location
