### ISSUE TITLE
Text Change 

### ISSUE THREAD

**Issue by sunyu912** [gamegala/gamegala.github.io#8]
"Application Process" => "Project Submission"

"All teams must also submit a link to a 2-min YouTube video of their project. The video must show a demo of the submitted project." => "All teams must also submit a link to a 2-min YouTube video of their project. The video must show a demo of the submitted project. The video must be uploaded to Youtube and submitted by Dec 2, 2018."

"Application Fees are not refundable. The only exception is for multiple payments for the same application." => "A $45 application fees are not refundable."

Add:

"The deadline to submit the project is 11:59pm Dec 2, 2018"

A button below to "Submit"

**Comment by cassilam** [comment]
Changed text and added a button
